### ISSUE TITLE
Find better images

### ISSUE THREAD

**Issue by cat5inthecradle** [dsmHack/dev.dsmhack.org#19]
Need some better images for:

- [ ] Wordpress
- [ ] Jamstack
- [ ] Cloud-Based

**Comment by cat5inthecradle** [comment]
Jamstack option: https://unsplash.com/photos/N7buN8Lv7uQ

**Comment by klieber** [comment]
> Jamstack option: https://unsplash.com/photos/N7buN8Lv7uQ

Haha.  I was thinking like a rock jam session but now I'm leaning this direction.

**Comment by klieber** [comment]
Wordpress options:

https://unsplash.com/photos/Zk--Ydz2IAs

https://unsplash.com/photos/-zRNvl3EUdw

https://unsplash.com/photos/fSqYwKWzwhk

https://unsplash.com/photos/O2MdroNurVw

**Comment by klieber** [comment]
Cloud is much more difficult:

https://www.needpix.com/photo/download/842616/cloud-computing-cloud-device-data-media-digital-laptop-network-online

https://pixabay.com/illustrations/cloud-computing-cloud-system-cloud-2153286/

https://www.pxfuel.com/en/free-photo-jrate

https://www.pxfuel.com/en/free-photo-qfxkt

https://www.needpix.com/photo/1028635/cloud-finger-smartphone-phone-typing-mobile-phone-screen-sms-send

https://www.piqsels.com/en/public-domain-photo-fjpbo

https://pixabay.com/illustrations/cloud-computer-backup-technology-3998880/

**Comment by klieber** [comment]
@cat5inthecradle I opened a PR so we could see a preview of what these look like.  Let me know if you like that or think we should try something else and I can update it:

https://deploy-preview-21--devdsmhackorg-99201.netlify.com/

**Comment by travissanderson-wf** [comment]
they look good to me, although there's something unsettling about the color of that jam... :D

**Comment by klieber** [comment]
I'm going to go ahead and go with those then and if we find better ones later we can always change them again.
